name: release

on:
  push:
    tags: ["v*.*.*"]

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v8
    with:
      prerelease: false
      release_files: rules_elide-v*.tar.gz
