name: release

on:
  push:
    tags: ["v*.*.*"]

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@1d798ff015ed0696433e01e2c3ccbb2abefadad7  # v7.7.0
    with:
      prerelease: false
      release_files: rules_elide-v*.tar.gz
